[mgr]

prepend_keymap = [
  { on = "M", run = "plugin mount" },
  { on = "o", run = "plugin open-with-cmd", desc = "Open with command" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  # disable file navigation wraparound
  { on = "k", run = "arrow -1", desc = "Previous file" },
  { on = "j", run = "arrow 1", desc = "Next file" },
  { on = "y", run = [
    'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
    # 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list',
    "yank",
  ] },
]
